version: '3.9'  
services:

  db:
    image: postgres:15-alpine
    container_name: inventree-db
    environment:
      POSTGRES_DB: inventree
      POSTGRES_USER: inventree
      POSTGRES_PASSWORD: inventree
    ports:
      - "5432:5432"
    volumes:
      - inventree-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: inventree-redis
    ports:
      - "6379:6379"

  inventree:
    image: inventree/inventree:latest
    container_name: inventree-server
    working_dir: /home/inventree/src/backend/InvenTree
    ports:
      - "8000:8000"
    environment:
      INVENTREE_SITE_URL: http://localhost:8000/
      INVENTREE_DB_ENGINE: django.db.backends.postgresql
      INVENTREE_DB_NAME: inventree
      INVENTREE_DB_USER: inventree
      INVENTREE_DB_PASSWORD: inventree
      INVENTREE_DB_HOST: db
      INVENTREE_DB_PORT: 5432
      INVENTREE_REDIS_HOST: redis
    depends_on:
      - db
      - redis
    entrypoint: []
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - inventree-data:/home/inventree/data
volumes:
  inventree-db-data:
  inventree-redis-data:
  inventree-data: