function uniqueSuffix() {
  // Keeps names stable-ish but unique across parallel workers.
  return `${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;
}

function partFactory(overrides = {}) {
  const suffix = uniqueSuffix();
  return {
    name: overrides.name ?? `UI Auto Part ${suffix}`,
    description: overrides.description ?? `Generated by Playwright UI automation (${suffix})`,
    ipn: overrides.ipn ?? `UI-${suffix}`.slice(0, 100),
    // Demo instance categories commonly include "Mechanical" (whereas "Passives" may not exist).
    categoryPath: overrides.categoryPath ?? ['Mechanical'],
  };
}

module.exports = {
  uniqueSuffix,
  partFactory,
};

